"""add nullable false

Revision ID: a28803b68c3e
Revises: 434892ddff12
Create Date: 2020-11-29 12:33:57.452115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a28803b68c3e'
down_revision = '434892ddff12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.drop_index('ix_task_created_at', table_name='tasks')
    op.drop_index('ix_task_updated_at', table_name='tasks')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.drop_index('ix_user_created_at', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_updated_at', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.create_index('ix_user_created_at', 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_task_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_index('ix_task_created_at', 'tasks', ['created_at'], unique=False)
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
