version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file:
      - ./app/.env
      - .env
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app/:/usr/src/app/
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
