FROM node:15 as frontend_build

COPY . .

RUN cd ./src/static && yarn install


FROM python:3.9

WORKDIR /usr/src/app
COPY --from=frontend_build . .

RUN pip install pipenv && pipenv install

CMD ["pipenv", "run", "flask", "run", "--host", "0.0.0.0", "--port", "$APP_PORT"]
