FROM node:15 as frontend_build

COPY . .

RUN cd ./src/static && yarn install


FROM python:3.9

WORKDIR /usr/src/app
COPY --from=frontend_build . .

RUN pip install pipenv && pipenv install

CMD ["pipenv", "run", "gunicorn", "--bind", "0.0.0.0:$APP_PORT", "wsgi:app"]
